version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "9001:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
